### ISSUE TITLE
10.12 public beta 4 中不能正常切换

### ISSUE THREAD

**Issue by happyeddie** [toolinbox/iHosts#10]
hosts文件改成777也不行

**Comment by atjason** [comment]
@happyeddie macOS Sierra 确实是有点问题，已经修复了，预计下周初上架 Mac App Store.

**Comment by happyeddie** [comment]
@atjason 赞效率 👍

**Comment by atjason** [comment]
@happyeddie 不客气，上架了我在这里通知你。

**Comment by toolinbox** [comment]
@happyeddie 新版已经上架 Mac App Store，支持 macOS Sierra.
