### ISSUE TITLE
字符问题导致hosts失效

### ISSUE THREAD

**Issue by DophinL** [toolinbox/iHosts#12]
![image](https://cloud.githubusercontent.com/assets/8707316/18032944/5cfaf3fc-6d49-11e6-9ff2-2f3f37ea6a3f.png)
这个^M是什么鬼啊。。。
才花了30块钱买就不能用，请速度解决

**Comment by toolinbox** [comment]
@DophinL 很抱歉给你带来麻烦了。

^M 通常是由于 Windows/Mac 的换行符不同引起的。参考：
https://www.zhihu.com/question/22130727

如果是使用复制、粘贴的方式来编辑
Hosts，可以先通过一些纯文本编辑器来中转。比如，将带格式的文本复制到纯文本编辑器中，然后再将纯文本编辑器中的文本复制后、粘贴到 iHosts 中。

由于要语法着色，iHosts 中的 Hosts 编辑器是带格式的，所以会有换行符不同而引起的问题。后期考虑在粘贴时去掉格式。暂时请先用上面的方法解决吧。

感谢支持 iHosts

**Comment by DophinL** [comment]
谢谢，确实是windows拷过来的问题，请问有账号系统吗？如果我换了电脑再安装还需要额外付款吗

**Comment by toolinbox** [comment]
@DophinL 恩，解决问题就好。顺便说下，可以了解下我的另一款 App: [贴贴板](http://toolinbox.net/clip/) 可以以纯文本粘贴，也可以解决类似的问题。

在别的 Mac 电脑中，只要使用相同的 Apple 账户登录，就可以在 iHosts 偏好设置 > 账户中 ”恢复“ 高级账户。如果恢复失败，可以尝试重新购买（不会重复扣款的）。如果遇到问题，可尝试删除 iHosts、重新安装后重试。
