### ISSUE TITLE
Additional features

### ISSUE THREAD

**Issue by Triloworld** [toolinbox/iHosts#16]
It will be nice to have possibility to have backup file in default mac keyring ;)
Second think: Before app edit host file, nice it will be to have one backup. 
Or better: history of hosts file editable in settings how long.
WiFi or Sound setting have hidden info when someone hold OPTION key when left click on icon. 
Could show number of settings enabled, full file or numbers of row. Nice when I compare to my coworker to check if have similar one :)
This is all key features that could have!
Thanks for it, I supporting it because it help me a lot 👍

**Comment by toolinbox** [comment]
@Triloworld Get your points for backup and show additionally info when press Option key to open iHosts menu. Thanks a lot for your suggestion.

I'm also happy you like iHosts. As you think iHosts is helpful, welcome to rate iHosts on Mac App Store and leave a small review. You know it will help me so much. Thanks in advance.

**Comment by Triloworld** [comment]
Review added because deserve it. Great in work and help to manage all host entries. 
Nobody need app to do everything so I wrote all possible features that can be implemented in topic of editing host file.
There is one more think. If i switch from disabled to enabled host then dns is flusched?
`dscacheutil -flushcache`

(no need sudo, but I don't know if is really nedeed in this situation)
https://www.liquidweb.com/kb/flush-dns-cache/

**Comment by toolinbox** [comment]
@Triloworld Thanks for your suggestion for `dscacheutil -flushcache`. 

In one side, I ever test and seems no need to do so. /etc/hosts has higher priority and it will be read first.
In another side, as iHosts runs in sandbox mode, it can't run extra command.
