### ISSUE TITLE
not support the new version of the mac system

### ISSUE THREAD

**Issue by Fury76** [toolinbox/iHosts#19]
when i upgrade mac sierra the new version, my iHosts can't be used.please support the new system as soon as possible.

**Comment by toolinbox** [comment]
@afu110 What's your iHosts's version? The latest one is v1.3.0.

I'm also using Sierra and iHosts works well. What's your problem exactly?

**Comment by Fury76** [comment]
sorry, i upgrade the iHosts to latest version. it was be supported. So that was my fault.

**Comment by toolinbox** [comment]
@afu110 Glad to know iHosts works now, thanks for your feedback.

Well, please help to [rate iHosts on App Store](https://itunes.apple.com/app/id1102004240?ls=1&mt=12) and leave your comments, thanks in advance.
