### ISSUE TITLE
很棒的软件！

### ISSUE THREAD

**Issue by charsen** [toolinbox/iHosts#20]
找了好久 hosts 管理软件，这个是最棒，已经升级 pro 版，期望继续更新！

希望能有导出导入功能，或者 icloud 备份，同步就更好了。

**Comment by atjason** [comment]
你好，
恩恩，记下了，感谢反馈。
既然觉得不错，帮忙在 App Store 给个好评、说说使用感受，入口就在 iHosts 菜单 > 更多 > 5 星好评，谢啦 :)
