### ISSUE TITLE
建议，为不同的配置设置颜色，让顶部的 logo 颜色表示现在的状态

### ISSUE THREAD

**Issue by fengyunhe** [toolinbox/iHosts#21]
建议，为不同的配置设置颜色，让顶部的 logo 颜色表示现在的状态

**Comment by atjason** [comment]
@fengyunhe 感谢建议。不过，如果同时选中 2 种不同颜色的配置，状态栏怎么显示呢？是个问题…

**Comment by fengyunhe** [comment]
大哥可搞如果是多个就颜色交替切换，让H变色
