### ISSUE TITLE
Icon indicator

### ISSUE THREAD

**Issue by cjh79** [toolinbox/iHosts#22]
I love this tool. Thank you for writing it. It's just what I needed.

One thing that I feel is missing is an indication in the menubar icon as to which nodes are selected. This would be incredibly helpful, as otherwise I find myself constantly having to look in the menu to see which hosts edits I'm using.

I realize this would be a UI challenge because multiple nodes can be selected. But even just a little badge which shows *how many* nodes are currently selected would be useful to many users, I think. For me, I am constantly turning on and off one particular node, so if I know at a glance that there are 2 selected vs. 1, that tells me all I need to know.

Thanks for your consideration and thanks again for a great app!

**Comment by atjason** [comment]
Hi @cjh79 Glad to know you like iHosts. 😀

Get your point. And you're right, _this would be a UI challenge because multiple nodes can be selected_. I will consider how to improve it, thanks for your great suggestion.

BR,
Jason

**Comment by mrmaloof** [comment]
How about changing the color of the indicator if the "default" hosts were not selected?

**Comment by atjason** [comment]
@mrmaloof I ever consider set color for each group or item, and then let colors of all selected groups/items to combine the circle in status bar, e.g.,

![](https://i.stack.imgur.com/DWsLK.png)

**Comment by mrmaloof** [comment]
Very cool! :thumbsup:
