### ISSUE TITLE
建议增加付费渠道

### ISSUE THREAD

**Issue by digimono** [toolinbox/iHosts#24]
免费版本升级到  Plus 版本需要30元，直接升级到Pro版需要50元，从Plus 升级到 Pro 版本也是50元，
能否增加内购方式以外的其它付费方式

**Comment by atjason** [comment]
@yqeric 你说的从 Plus 从 Pro 升级确实是个问题，不过目前 App Store 里对这种方式的升级不支持特殊的处理，所以…在 App Store 之外升级确实能解决这个问题，不过要另外实现支持、序列号管理等等，也挺麻烦，我再考虑下。谢谢你的反馈。

目前，如果你需要从 Plus 升级到 Pro 的话，[可以联系我退差价](https://toolinbox.net/html/feedback.html?lang=en-CN)。
