### ISSUE TITLE
mac book pro 下进程僵死

### ISSUE THREAD

**Issue by winter-hi** [toolinbox/iHosts#25]
> cat net.toolinbox.ihosts\ 2017-03-21\ 11-32.log
2017/03/21 19:32:32:633  Retrieve product failed code: 0. Invalid products: ["net.toolinbox.ihosts.pro"]
2017/03/21 19:32:32:722  Retrieve product failed code: 0. Invalid products: ["net.toolinbox.ihosts.plus"]

**Comment by atjason** [comment]
你好，请问你是做了什么操作？具体是什么表现？

**Comment by winter-hi** [comment]
升级版本后解决啦
<img width="335" alt="wx20170321-201838 2x" src="https://cloud.githubusercontent.com/assets/8273770/24147082/9da968cc-0e73-11e7-9a4c-2b1e78bdc013.png">

**Comment by atjason** [comment]
@wenpengHao 恩，这就好。
