### ISSUE TITLE
多个host方案时，状态栏点击ihosts，在各个方案移动预览时有卡顿

### ISSUE THREAD

**Issue by WillisLing** [toolinbox/iHosts#28]
多个host方案时，状态栏点击ihosts，出现列表，鼠标在各个方案移动预览时有卡顿（只要出现了预览视图后，快速上下移动就会卡顿明显）。

建议在设置中，加一个开关，可以关闭预览功能。

**Comment by atjason** [comment]
恩，这个可以有。

**Comment by atjason** [comment]
可以在偏好设置中关闭预览功能。
