### ISSUE TITLE
Feature Request: Export config

### ISSUE THREAD

**Issue by gabrielboley** [toolinbox/iHosts#29]
Hello,

Wanted to say thanks for the app, I use it multiple times on a daily basis and I've helped convince a few colleagues to switch over from the common Gas Mask host application to iHost. So much better!

I was wondering if it were possible to export your host files to something that could then be imported again into iHosts. Working in a commercial environment, we have a lot of test servers that we are constantly switching back and forth to and we are always hiring new developers so we would love the ability to export our configs and share them with other devs.

Another nice feature would be some kind of auto dns flush on change. Switch we are generally testing the same app/site on different servers we are always fighting local cache to get the content we want. If iHosts could flush our dns then that would be even better.

Thanks again!

Gabe

**Comment by atjason** [comment]
@nyxerus Glad to know iHosts is helpful for you.

For 'export config', great suggestion.

For 'flush dns', you can consider `dscacheutil -flushcache` now. iHosts will try to do it, but possibly has problem as it's in sandbox mode.

BR,
Jason
