### ISSUE TITLE
状态栏的图标不太喜欢

### ISSUE THREAD

**Issue by rockytan** [toolinbox/iHosts#3]
我也就能提提意见哈，不太喜欢一个孤零零的 H 挂在状态栏，个人喜好问题

**Comment by toolinbox** [comment]
我其实也不太满意；其实想过好多版本，比如下面这种比较酷炫的：

![](http://ww2.sinaimg.cn/large/006ghf8igw1f3v13s1772j304e01ojr6.jpg)

但放在状态栏里显得太复杂了。

下版可能只是简单调整下，看起来更像是个字母 H，如下，你觉得呢？

![](http://ww2.sinaimg.cn/large/006ghf8igw1f3v12jvfc8j30di01yq2x.jpg)

**Comment by rockytan** [comment]
哈哈，我觉得那个像D的蛮不错，我对 Mac 开发不太了解，这个 icon 可以定制吗？

**Comment by toolinbox** [comment]
@rockytan 这个图标是开发者自己提供的，应该就是你说的“可以定制”。对上面微调后的 H 还不满意？好吧，我再努力努力~

**Comment by rockytan** [comment]
这么晚还没休息呢？你可能理解错我的意思了，我的意思是 Mac 的 app 显示在 Dock 上的 icon 是可以用户自己更换的，找一个 icon 就可以替换，我的问题是 menu 栏的 icon 是不是可以由用户自己替换，而不是开发者预先放在 app 里面的。我是服务端开发，可能对 app 和 client 的一些东西不是特别理解。
其实你也不用太在意我的意见，我美感比较差，哈哈。

**Comment by toolinbox** [comment]
@rockytan 恩，是可以换的；也就是说，理论上可以用户自己传个图片作为这个图标。

不过，这个图标本身的尺寸很小，设计难度反而变大。基本上，没有设计过的图片是用不了的 ...

美丑确实很难说，也有 App 是预置多个图标让用户选。但我感觉那是因为作者没有找到更好的图标，我应该不会这么做。

刚刚完成了另一个 App 的小样，感兴趣可以到这里看看：http://v2ex.com/t/279104

**Comment by toolinbox** [comment]
@rockytan 暂时先关闭这个 issue 了，以后会继续想着改进图标的，谢谢反馈。
