### ISSUE TITLE
啥时候出备份导入，或同步到 iCloud?

### ISSUE THREAD

**Issue by charsen** [toolinbox/iHosts#30]
RT！几个月没更新了，期望这个需求得到解决，谢谢！

**Comment by atjason** [comment]
@charsen 目前在赶工 [Klib](http://klib.me/cn/)，这个功能可能还得再等等了，抱歉。

**Comment by WillisLing** [comment]
备份导出与导入，都是急需的

**Comment by charsen** [comment]
@atjason 什么时候可以解决呢？快一年时间啦！

**Comment by charsen** [comment]
我都推荐给公司同事用了，要能直接用 icloud 最好，不能的话，就导入导出，也可以满足一般需求了。

**Comment by atjason** [comment]
@charsen @WillisLing  抱歉了，暂无计划。

**Comment by charsen** [comment]
@atjason 有些失望，那你能告诉我，本地的文件是存在哪吗？我自己拷贝出来备份也可以。

**Comment by atjason** [comment]
@charsen 在 plist 文件中，不过是黑盒数据，用来备份可以，但不方便在不同电脑间互通。

~/Library/Containers/net.toolinbox.ihosts/Data/Library/Preferences/net.toolinbox.ihosts.plist

**Comment by charsen** [comment]
@atjason 应该有不付费用户吧，排个计划升级一下吧。

iHosts 是很不错的软件，总不能原地踏步吧
