### ISSUE TITLE
缓存刷新问题

### ISSUE THREAD

**Issue by DayThink** [toolinbox/iHosts#34]
当切换host后，每次都需要重启一下浏览器，能否加上不重启浏览器就自动刷新缓存或添加一个能刷新缓存的按钮。

**Comment by atjason** [comment]
@DayThink 浏览器有自己的缓存机制，iHosts 无法控制。

**Comment by aiddroid** [comment]
@atjason  好像我执行一次 dscacheutil -flushcache 就好了

**Comment by atjason** [comment]
@aiddroid 这个我了解，能更新 macOS DNS 缓存，只是有时侯 Chrome 比较顽固…
