### ISSUE TITLE
会出现cpu占用90%+的情况

### ISSUE THREAD

**Issue by dirtytao** [toolinbox/iHosts#37]
会出现cpu占用90%+的情况

**Comment by atjason** [comment]
技术上的原因，在显示菜单后，再弹出预览窗口，有可能会出现这个问题。目前，尽量避免在菜单中预览 hosts 内容，可以规避这个问题。

**Comment by dirtytao** [comment]
后续版本会修复吗？ @atjason

**Comment by atjason** [comment]
@dirtytao 技术上可能无解，估计会去掉这个功能，或者加个开头项。

**Comment by dirtytao** [comment]
@atjason  兄弟，这个功能赶紧去掉哈，或者加个配置开关也行，我现在不定期触发这个问题。😱😱

**Comment by wanpg** [comment]
我也遇到了这个问题，很容易出发预览的，希望能去掉，改成别的预览方式

**Comment by winter-hi** [comment]
也遇到这个问题，开始以为是没有付费，付费后发现还是有问题。是否有开关关闭预览选项？

**Comment by winter-hi** [comment]
@atjason 是否有修改配置文件方式，关掉这个功能啊

**Comment by atjason** [comment]
@dirtytao @wanpg @wenpengHao 可以在 iHosts 偏好设置中，关掉预览功能。
