### ISSUE TITLE
很棒的软件，有没有人愿意做一个brew formula

### ISSUE THREAD

**Issue by thinkd1ff** [toolinbox/iHosts#39]
很棒的软件，有没有人愿意做一个brew formula

**Comment by Mitscherlich** [comment]
已经提交了 PR，过段时间应该就可以下了。

原作者只提供了到 v1.2.5 的 bundle，所以该 formula 现在最高版本也是 v1.2.5，需要最新版的请移步 [Mac App Store 上的“iHosts - 编辑神器”](https://itunes.apple.com/cn/app/ihosts/id1102004240?mt=12)

**Comment by thinkd1ff** [comment]
ths
