### ISSUE TITLE
Unlimited hosts

### ISSUE THREAD

**Issue by thps** [toolinbox/iHosts#4]
I noticed the Pro version only allows 50 host nodes. That seems like an arbitrary limit. Any reason why it can't be unlimited and we would get more utility out of the tool? With larger micro service development it is conceivable that more than 50 host nodes would be useful. I would be happy to pay for the pro if it was unlimited just to know I did not have a limitation. The price difference isn't that great.

**Comment by toolinbox** [comment]
Hi, thanks for your feedback.
In fact in the beginning it was planned to set the limit for Pro to be 20 host nodes. As it's already many enough. And it will let the menu to be very long and hard to use. But still, it was set to 50. Try to image a menu with 50 menu items...

Maybe another choice of 'iHosts Unlimited' could also answer your question :)

Hope iHosts is helpful for you.

**Comment by toolinbox** [comment]
@thps The new version of iHosts is already released on Mac App Store, which already supports macOS Sierra. In another side, Pro users could create unlimited hosts nodes. Hope you like it.
