### ISSUE TITLE
iHost Functioning weird with a site

### ISSUE THREAD

**Issue by rgluger** [toolinbox/iHosts#40]
Hello,
I have two sites hosted in the same server, different cpanels.
I added the two sites> IPADDRESS SITE
I see one site and the other I don't how is this possible?
Thanks!

www.aisaijiri.com (points to where I established 
www.webelieveinbeauty.com (still points to the old site and not to server)

All checked> spelling, IP, etc

SAMEIP webelieveinbeauty.com 
SAMEIP aisaijiri.com

**Comment by atjason** [comment]
How you test? How about ping in Terminal? If ping is fine but not fine in Chrome or other browser, maybe caused by the cache of the browser itself.

`ping webelieveinbeauty.com`
`ping www.aisaijiri.com`
