### ISSUE TITLE
每次选择 Host 之后，都需要注销用户或者重启才能生效

### ISSUE THREAD

**Issue by roveim** [toolinbox/iHosts#5]
系统：macOX 10.11

会不会和使用了代理（Surge for mac） 有关？

**Comment by toolinbox** [comment]
你好，
这个事情还是有点复杂的。

iHosts 本质上是替代手动修改 /etc/hosts，如果修改 /etc/hosts 做不到的事，iHosts 也做不到。可以做个测试，在 iHosts 中添加一个记录：127.0.0.1 sohu.com，然后在 Terminal 中 ping sohu.com，如果看到的是 127.0.0.1，说明 iHosts、及 /etc/hosts 的修改没有问题。

然后再说“生效”，“生效”是对应应用的，比如在上面 Terminal 中，就是生效的。但对别的应用，就不一定的。你说的是哪个应用？
对于 浏览器（如 Chrome）+ 代理的组合，我没用过 Surge，但用的是 ShadowSocks。在 SS 的自动模式中，浏览器还是会去 /etc/hosts 中取相关记录。但如果是全局模式，就只会从 SS 中取记录、绕过 /etc/hosts 的。这时 iHosts 也是无能为力的。

你试试，确定下情况。

**Comment by roveim** [comment]
谢谢细心回复。ping 的时候是修改后的 host，说明已经成功修改了。
我用的是Surge 全局代理，Chrome 浏览器，现在做法是关掉 Surge 切换 Host 就可以了。多谢啦

**Comment by atjason** [comment]
恩，不客气，有问题继续来反馈。
