### ISSUE TITLE
iHosts hight cpu usage

### ISSUE THREAD

**Issue by eric68668** [toolinbox/iHosts#50]
![image](https://user-images.githubusercontent.com/8872258/47125764-db9abf00-d2b7-11e8-9976-25b0bd4398b3.png)

![image](https://user-images.githubusercontent.com/8872258/47125788-f10fe900-d2b7-11e8-84d0-c5612b1364ee.png)

Ver: 1.3.0
MacOS: 10.14

**Comment by atjason** [comment]
Please don't mouse over menu item to preview hosts, which may caused this issue in some cases. Consider to remove this feature later.

**Comment by atjason** [comment]
You can disable 'Preview hosts when mouse over' in Preferences.
