### ISSUE TITLE
Could this tool open sourced?

### ISSUE THREAD

**Issue by cwtuan** [toolinbox/iHosts#51]
I would like to add some functionality to it, please make it open sourced?

**Comment by atjason** [comment]
No such plan. What feature you want to add?

**Comment by cwtuan** [comment]
We have a hosts file located on the internet. Is it possible ihost synchronizedd with this file via http? User can input the url of that file in ihost.

**Comment by atjason** [comment]
Get it. Sorry but iHosts doesn't support it.

**Comment by cwtuan** [comment]
Thanks, anyway.
Will you consider support this feature in the future?
