### ISSUE TITLE
Host Nodes

### ISSUE THREAD

**Issue by michael-grunewalder** [toolinbox/iHosts#57]
Hi, 
your tool is awesome and makes it very convenient to edit the host file. 
I used to do it with "sudo pico" but now it is so much more convenient.

Could you tell me what counts as a "Host Node"?

**Comment by atjason** [comment]
Hi, like this:
![21-16-26](https://user-images.githubusercontent.com/803199/159924295-23f855d8-ca16-4cc5-8be8-cc28542dd5f0.jpg)
