### ISSUE TITLE
某些情况会导致localhost失效

### ISSUE THREAD

**Issue by ficapy** [toolinbox/iHosts#6]
当不选择default的时候,会出现如下情况

```
ping localhost                                         
ping: cannot resolve localhost: Unknown host
```

这会导致一些软件无法使用 比如使用httpie执行`http :8000`

**Comment by ficapy** [comment]
建议把一些最基本的host加上

**Comment by toolinbox** [comment]
因为 default 中包含一些基本的解析，禁用这些选项，就会带来你说的问题。
127.0.0.1 localhost
255.255.255.255 broadcasthost
::1             localhost

**Comment by ficapy** [comment]
这些最基本的host是有用的。我认为即使不选择default也应该保留这些基本的host
这样会好一点吧

**Comment by atjason** [comment]
恩，你这么说也有道理。目前，可以把必选的 Host 设置放在 Default 中，不去管它。把需要切换的 Host 单独放在分组或节点中。
