### ISSUE TITLE
安装 macOS Sierra 预览版后无法编辑和切换hosts

### ISSUE THREAD

**Issue by YangJianchong** [toolinbox/iHosts#7]
状态栏的下拉菜单里点击不同的节点却没反应, hosts也没有更改

**Comment by atjason** [comment]
@YangJianchong 感谢反馈；坦白讲，iHosts 还没做 Sierra 兼容的事，近期就会改进的。

**Comment by toolinbox** [comment]
@YangJianchong 新版已经上架 Mac App Store，支持 macOS Sierra.
