### ISSUE TITLE
每次启动都会要求运行命令行，获得 /etc/hosts 权限。

### ISSUE THREAD

**Issue by david9991** [toolinbox/iHosts#9]
El Captain 每次重启都要求运行 sudo /bin/chmod +a 'user:David:allow write' /etc/hosts，好像每次重启系统都检测一次 permission 把 hosts 文件权限重置了，是否可以安装后把这个命令直接做在 launchDaemon 里，每次启动再重设一遍 acl？

**Comment by pocographdotcom** [comment]
`

`

**Comment by david9991** [comment]
点错了……

**Comment by atjason** [comment]
@pocographdotcom 因为 iHosts 是沙盒应用，做不到”把这个命令直接做在 launchDaemon 里“。

**Comment by david9991** [comment]
好吧，看来只能自己人工配了。

**Comment by atjason** [comment]
@pocographdotcom 不好意思了；那我把这个 issue 关闭了。之后我再想想办法。

**Comment by willin** [comment]
有什么手工配置的教程么？？？ @toolinbox @atjason

**Comment by willin** [comment]
Helm 就不需要这个权限 可以参考一下？

**Comment by atjason** [comment]
@willin 奇怪，怎么我就一直没遇到过这个问题…

App Store 沙盒的限制，注定了 iHosts 本身是无法修改 /etc/hosts 的权限的。如果确实是 macOS 自动重置了 /etc/hosts 的权限，可以考虑将 `/bin/chmod +a 'user:David:allow write' /etc/hosts` 这样的命令放到 su 的 crontab 中，每次启动时设置。

最后，貌似我很少重启 Mac…

**Comment by willin** [comment]
@atjason  已找到解决方案，并使用 node.js 测试成功。如果该项目用 electron 实现，我可以贡献代码。

**Comment by atjason** [comment]
@willin 棒，请问下原理是？iHosts 是使用 Swift 开发的。

**Comment by willin** [comment]
测试时候写了一句：


```bash
sudo /bin/chmod +a 'user:David:deny write' /etc/hosts
```

导致iHosts 再也无法用了，再用 allow 也不行了。@atjason 知道为什么吗

**Comment by atjason** [comment]
@willin 首先去除 deny 限制，即将语句中 `+a` 改为 `-a` 即可：
`sudo /bin/chmod -a 'user:David:deny write' /etc/hosts`

然后重新授权：
`sudo /bin/chmod +a 'user:David:allow write' /etc/hosts`

**Comment by willin** [comment]
```bash
sudo -n -u willin -p pass /bin/chmod +a 'user:willin:allow write' /etc/hosts
```

pass 不能有符号，如 ! 之类的

会报错

```
zsh: event not found:  !之后内容
```

而且不能直接确认文件权限。。。 用 File System 又很麻烦。

**Comment by atjason** [comment]
@willin 不太理解你上面说的，直接运行 `sudo /bin/chmod +a 'user:willin:allow write' /etc/hosts` 不行吗？另外，永远不要在命令行文本中直接输入密码，不安全；而要在出现密码提示、没有回显时再输入。
